[site]
title = "Rockgarden"
clean_urls = true
output = "../_site"
ignore_patterns = []

[dates]
timezone = "US/Eastern"

[theme]
nav_default_state = "expanded"

[nav]
sort = "files-first"

[[nav.links]]
label = "Tags"
url = "/tags/"

[[nav.links]]
label = "GitHub"
url = "https://github.com/rockgarden-build"
